### ISSUE TITLE
Request to add product icons to ux.redhat.com

### ISSUE THREAD

**Issue by alazzara** [RedHat-UX/red-hat-icons#2]
After talking with Dan Caryll. There is a need to add the following files in a section titled `product icons` to the page in this mockup https://xd.adobe.com/view/ed068856-161b-49cf-b44c-da395a26c0b4-b855/.

**Product icons to be added:**
https://gitlab.corp.redhat.com/uxdd/brand-assets/-/tree/main/src/product-icons

The files in the above repo end up on static inside this folder: https://static.redhat.com/libs/redhat/brand-assets/2/product-icons/, so links to the icons on this page should point to the corresponding URL on static.

**Example:**
product-icon-red-hat-runtimes
Should point to https://static.redhat.com/libs/redhat/brand-assets/2/product-icons/product-icon-red-hat-runtimes.svg

**FYI:** 
I imagine this will get more files added over time that will be added to the repo listed above and ultimately end up on static. Let me know how you want to handle this in the future.

**Comment by bennypowers** [comment]
blocked by https://github.com/RedHat-UX/red-hat-icons/pull/1/

**Comment by markcaron** [comment]
If I recall correctly from a convo with @ryawilli, I don't believe Brand wants us adding product icons to the repo.
